package main.java.com.github.felipeabdiel.t13;

public class Partida {
    public static void main(String[] args) {
        Jogador jogadorBrancas = new Jogador("Adolf Anderssen");
        Jogador jogadorNegras = new Jogador("Lionel Kieseritsky");

        Peca Peao = new Peca("Peão");
        Peca Cavalo = new Peca("Cavalo");
        Peca Bispo = new Peca("Bispo");
        Peca Torre = new Peca("Torre");
        Peca Dama = new Peca("Dama");
        Peca Rei = new Peca("Rei");

        Posicao lance1b = new Posicao('E', 4);
        Posicao lance1n = new Posicao('E', 5);
        Posicao lance2b = new Posicao('F', 4);
        Posicao lance2n = new Posicao('F', 4);
        Posicao lance3b = new Posicao('C', 4);
        Posicao lance3n = new Posicao('H', 4);
        Posicao lance4b = new Posicao('F', 1);
        Posicao lance4n = new Posicao('B', 5);
        Posicao lance5b = new Posicao('B', 5);
        Posicao lance5n = new Posicao('F', 6);
        Posicao lance6b = new Posicao('F', 3);
        Posicao lance6n = new Posicao('H', 6);
        Posicao lance7b = new Posicao('D', 3);
        Posicao lance7n = new Posicao('H', 5);
        Posicao lance8b = new Posicao('H', 4);
        Posicao lance8n = new Posicao('G', 5);
        Posicao lance9b = new Posicao('F', 5);
        Posicao lance9n = new Posicao('C', 6);
        Posicao lance10b = new Posicao('G', 4);
        Posicao lance10n = new Posicao('F', 6);
        Posicao lance11b = new Posicao('G', 1);
        Posicao lance11n = new Posicao('B', 5);
        Posicao lance12b = new Posicao('H', 4);
        Posicao lance12n = new Posicao('G', 6);
        Posicao lance13b = new Posicao('H', 5);
        Posicao lance13n = new Posicao('G', 5);
        Posicao lance14b = new Posicao('F', 3);
        Posicao lance14n = new Posicao('G', 8);
        Posicao lance15b = new Posicao('F', 4);
        Posicao lance15n = new Posicao('F', 6);
        Posicao lance16b = new Posicao('C', 3);
        Posicao lance16n = new Posicao('C', 5);
        Posicao lance17b = new Posicao('D', 5);
        Posicao lance17n = new Posicao('B', 2);
        Posicao lance18b = new Posicao('D', 6);
        Posicao lance18n = new Posicao('G', 1);
        Posicao lance19b = new Posicao('E', 5);
        Posicao lance19n = new Posicao('A', 1);
        Posicao lance20b = new Posicao('E', 2);
        Posicao lance20n = new Posicao('A', 6);
        Posicao lance21b = new Posicao('G', 7);
        Posicao lance21n = new Posicao('D', 8);
        Posicao lance22b = new Posicao('F', 6);
        Posicao lance22n = new Posicao('F', 6);
        Posicao lance23b = new Posicao('E', 7);

        Peca peca1b = new Peca("Peão");
        Peca peca1n = new Peca("Peão");
        Peca peca2b = new Peca("Peão");
        Peca peca2n = new Peca("Peão");
        Peca peca3b = new Peca("Bispo");
        Peca peca3n = new Peca("Dama");
        Peca peca4b = new Peca("Rei");
        Peca peca4n = new Peca("Peão");
        Peca peca5b = new Peca("Bispo");
        Peca peca5n = new Peca("Cavalo");
        Peca peca6b = new Peca("Cavalo");
        Peca peca6n = new Peca("Dama");
        Peca peca7b = new Peca("Peão");
        Peca peca7n = new Peca("Cavalo");
        Peca peca8b = new Peca("Cavalo");
        Peca peca8n = new Peca("Dama");
        Peca peca9b = new Peca("Cavalo");
        Peca peca9n = new Peca("Peão");
        Peca peca10b = new Peca("Peão");
        Peca peca10n = new Peca("Cavalo");
        Peca peca11b = new Peca("Torre");
        Peca peca11n = new Peca("Peão");
        Peca peca12b = new Peca("Peão");
        Peca peca12n = new Peca("Dama");
        Peca peca13b = new Peca("Peão");
        Peca peca13n = new Peca("Dama");
        Peca peca14b = new Peca("Dama");
        Peca peca14n = new Peca("Cavalo");
        Peca peca15b = new Peca("Bispo");
        Peca peca15n = new Peca("Dama");
        Peca peca16b = new Peca("Cavalo");
        Peca peca16n = new Peca("Bispo");
        Peca peca17b = new Peca("Cavalo");
        Peca peca17n = new Peca("Dama");
        Peca peca18b = new Peca("Bispo");
        Peca peca18n = new Peca("Bispo");
        Peca peca19b = new Peca("Peão");
        Peca peca19n = new Peca("Dama");
        Peca peca20b = new Peca("Rei");
        Peca peca20n = new Peca("Cavalo");
        Peca peca21b = new Peca("Cavalo");
        Peca peca21n = new Peca("Rei");
        Peca peca22b = new Peca("Dama");
        Peca peca22n = new Peca("Cavalo");
        Peca peca23b = new Peca("Bispo");
    }

}
